export const brands = [
  {
    handle: 'absolute-essential',
    name: 'Absolute Essential',
    tagline: 'Trusted, purposeful and made with genuine expertise, Absolute Essential is plant medicine taken seriously.',
    vendor_match: 'Absolute Essential',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Born at a kitchen table in Aotearoa, Absolute Essential began in 1988 when Dr Bo Hendgen, a naturopath, osteopath and aromatic medicine practitioner who had trained in France, found she could not source essential oils of the quality her clinical practice required. So she began sourcing her own, and from that necessity something enduring grew.',
      'The brand works exclusively within the four percent of the world\'s essential oils made to genuine medicinal standards, drawing on certified organic and wild-grown plant extracts from small artisan communities across 59 countries. Slower distillation and extraction methods are used throughout, preserving the delicate therapeutic compounds that give each oil its real potency.',
      'There is a rigour to Absolute Essential that feels both scientific and deeply human, the result of three decades of clinical practice, ethical sourcing and an unwavering belief in the healing intelligence of plants.',
      'Each product is formulated to support safe, confident use within everyday wellbeing rituals, bringing the medicinal quality of the plant world into ordinary daily life.',
    ],
  },
  {
    handle: 'alexandra-beauty',
    name: 'Alexandra Beauty',
    tagline: 'Simple, clean and quietly devoted to natural radiance, Alexandra Beauty offers skincare as an act of protection and love.',
    vendor_match: 'Alexandra',
    collection_handle: '',
    published: true,
    paragraphs: [
      'The name Alexandra carries the meaning of protection, and that intention is woven into everything this brand makes.',
      'Created as the sister brand to Amber & Gold, Alexandra Beauty is an organic skincare brand focusing specifically on skincare, formulated entirely from organic natural ingredients chosen to support, replenish and gently nourish. The range can be used across the face, body and hair, and its gentle formulations make it particularly well suited for sensitive skin.',
      'Amber & Gold was designed to move across the wider landscape of wellbeing and Alexandra Beauty focuses attention to the skin itself, what it needs for deep nourishment and luminosity.',
      'The approach is unhurried and purposeful, shaped by the same philosophy of care and consciousness that defines its sister brand.',
    ],
  },
  {
    handle: 'amber-and-gold',
    name: 'Amber & Gold',
    tagline: 'Earthy, nurturing and genuinely devoted, Amber & Gold is crafted with intent.',
    vendor_match: 'Amber & Gold',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Amber & Gold was created with reverence, for the body, for the earth and for the synergy between the two.',
      'The sister brand to Alexandra Beauty, Amber & Gold focuses on herbal tea blends and flower essences designed to support the body from within, moving across the wider landscape of wellbeing.',
      'The brand\'s philosophy is one of care, consciousness and integrity, where every product is made to support both people and place without asking one to be compromised for the other.',
      'Sustainably sourced organic ingredients are chosen for their purity and their alignment with the body\'s own intelligence, nothing excessive, nothing that doesn\'t belong.',
      'Each formulation is made slowly, reflecting a belief that what we consume and how we care for ourselves matters.',
    ],
  },
  {
    handle: 'aotea',
    name: 'Aotea',
    tagline: 'Grounded, restorative and woven into the landscape that sustains it, Aotea offers skincare that is as much about belonging as it is about beauty.',
    vendor_match: 'Aotea',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Aotea, Great Barrier Island, sits far offshore, one of the most remote and unspoiled places in Aotearoa, where the land holds an extraordinary quality of stillness and wildness in equal measure.',
      'It is from this papakāinga that the Aotea skincare brand grows, drawing on mātauranga Māori and rongoā Māori to bring together traditional plant knowledge and thoughtful modern formulation.',
      'Native botanicals are grown, extracted and prepared on the land itself, giving each product an unbroken connection to place, people and whenua that cannot be replicated elsewhere.',
      'Formulated and bottled by hand in small batches, the range carries the character of the island, its wildness, its deep quiet, its profound relationship with the natural world.',
      'To use it is to be connected, however briefly, to a place and a practice that remembers what it means to truly care for the skin and the earth together.',
    ],
  },
  {
    handle: 'artemis',
    name: 'Artemis',
    tagline: 'Wise, purposeful and genuinely trustworthy, Artemis offers herbal care that has been believed in across centuries, made now for the rhythms of modern everyday life.',
    vendor_match: 'Artemis',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Dr Sandra Clair\'s knowledge of plant medicine began in Switzerland, shaped by a tradition of herbal practice that understands plants not as supplements but as medicine, proven by generations of use and deserving of genuine scientific rigour.',
      'She brought that knowledge with great care to Aotearoa New Zealand, where Artemis was born: a brand of teas, tonics and herbal preparations grounded in both traditional wisdom and modern understanding.',
      'Each formulation is made with deep respect for the plants it works with and the people it is intended to support, guided by the principle of kaitiakitanga, the understanding that as we care for the earth, she cares for us in return.',
      'Nothing is formulated for trend or convenience. Everything is made because it has earned its place through a long lineage of knowledge and practice.',
    ],
  },
  {
    handle: 'bepure',
    name: 'BePure',
    tagline: 'Practical, honest and grounded in genuine expertise, BePure brings considered nutritional support into the rhythms of everyday wellbeing.',
    vendor_match: 'BePure',
    collection_handle: '',
    published: false,
    paragraphs: [
      'BePure was founded by clinical nutritionist Ben Warren on a belief that feels simple but carries real weight: modern life places genuine demands on the body, and considered nutritional support can help restore balance without overcomplicating things.',
      'The brand draws on over 20 years of clinical experience, holistic health principles and scientific research to create supplements that offer the body what it actually needs, and nothing beyond that.',
      'Each formulation is made with transparency and purpose, designed to work with the body\'s natural intelligence rather than override or replace it.',
      'BePure approaches health as something supported over time, through daily ritual and the kind of consistent, thoughtful care that accumulates into something meaningful.',
    ],
  },
  {
    handle: 'chakra',
    name: 'Chakra',
    tagline: 'Earthy, intentional and softly spiritual, Chakra offers ancient practices made accessible for a modern life that needs them.',
    vendor_match: 'Chakra',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Palo santo from Peru, sage from the high desert, crystals drawn from the earth in Madagascar, Morocco, Brazil, Africa and Pakistan. Chakra sources ritual objects from places where these materials have been gathered and used for centuries.',
      'The brand is guided by genuine care in its sourcing, working with suppliers who share both its ethics and its understanding of what these objects carry, meaning, history and the particular energy of the land they come from.',
      'Each piece is chosen to support daily practices of grounding, cleansing and return, a stick of palo santo lit at the end of a long day, a crystal held in the quiet of morning, sage carried through a new space.',
      'These are not decorative objects. They are tools for presence, for breath, for finding the thread back to oneself.',
    ],
  },
  {
    handle: 'charlotte-penman',
    name: 'Charlotte Penman',
    tagline: 'Romantic, talismanic and full of genuine soul, Charlotte Penman creates pieces that carry something, and find the people who need them.',
    vendor_match: 'Charlotte Penman',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Charlotte Penman came to jewellery through a lineage of makers, artists and travellers, people who understood that what we choose to wear close to the body carries something beyond the decorative.',
      'Her work is shaped by a love of gemstones, symbolism and the intimate meaning held in adornment: the ring that marks a moment, the pendant worn as a daily talisman, the earring that catches light at exactly the right time.',
      'Each piece brings a bohemian sensibility together with a classical and enduring sense of form, jewellery that feels at once personal and timeless, worn as amulet, keepsake or quiet armour for the everyday.',
      'Charlotte designs for those who choose what they wear with feeling, who understand that jewellery is not an accessory but a language.',
    ],
  },
  {
    handle: 'come-clean',
    name: 'Come Clean',
    tagline: 'Gentle, honest and made in Aotearoa with genuine care, this is body care extended to its most intimate expression.',
    vendor_match: 'Come Clean',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Come Clean begins with a simple premise: that intimacy deserves the same care and integrity we bring to every other act of wellbeing.',
      'Made in Aotearoa from all-natural ingredients, this water-based lubricant is formulated with organic New Zealand hemp and soothing aloe vera, pH-balanced, vegan, free from glycerin and synthetic fragrance, and endorsed by naturopaths who understand what the body actually needs.',
      'The formulation is clean, considered and completely without compromise, because the most personal rituals of all should never require us to accept less than the best.',
      'Silky, hydrating and leaving nothing behind but softness and ease, Come Clean offers a more conscious approach to intimacy, one that feels as natural as touch itself.',
    ],
  },
  {
    handle: 'coskin',
    name: 'CoSkin',
    tagline: 'Honest, purposeful and rooted in genuine understanding, CoSkin offers simple, everyday support for the skin we live in.',
    vendor_match: 'CoSkin',
    collection_handle: '',
    published: true,
    paragraphs: [
      'CoSkin began not in a laboratory but in a family, founded by Dr Alistair and Stephanie Lane after their son reacted adversely to everyday household products. That experience led them to plant oils, aromatherapy and natural formulation, and from that personal search something genuinely useful was built.',
      'The brand is best known for its anhydrous, waterless sunscreen and moisturiser, formulated using a plant oil base that delivers nourishment and protection without the heavy feel of conventional products. Ingredients are chosen for their therapeutic qualities, drawing on the science of aromatherapy alongside added vitamins and antioxidants to support skin health.',
      'Each product is made to nourish, protect and support the skin in the way that daily life actually demands, practical, kind and grounded in natural science.',
    ],
  },
  {
    handle: 'dwyer',
    name: 'Dwyer',
    tagline: 'Local, handcrafted and quietly luxurious, Dwyer creates beauty that lingers softly and means something.',
    vendor_match: 'Dwyer',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Sarah Dwyer is a Matakana perfumer and maker whose work is guided by a deep love of scent, place and the memories that fragrance can hold. Working from her studio, she blends and bottles perfumes and facial oils by hand in small batches, using exquisite oils and absolutes sourced locally and from around the world.',
      'Each formulation is chosen for both its function and its sensory depth, designed to sit gently on the skin while offering something more to the senses. Fragrance and skincare are approached here as daily rituals, grounding, uplifting and quietly transformative in the way that only things made with genuine care can be.',
      'The range is small, considered and deeply personal, rooted in ethical sourcing and a slower approach to beauty that never compromises on integrity.',
    ],
  },
  {
    handle: 'eco-art',
    name: 'Eco Art',
    tagline: 'Gentle, meditative and softly luminous, Eco Art brings natural warmth into the home in its most honest form.',
    vendor_match: 'Eco Art',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Daniela Kowhai makes candles in Northland the way candles were always meant to be made, slowly, by hand, from pure New Zealand beeswax and an unbleached cotton wick.',
      'Her studio practice, Eco Art, is rooted in traditional hand skills, natural materials and a genuinely low-impact way of living that extends from how the candles are made to what they are made from.',
      'Pure beeswax burns cleanly and carries a faint natural warmth, a quality that synthetic waxes cannot replicate, no matter how carefully they are formulated.',
      'Daniela preserves that quality in every piece, working slowly enough to honour the material and the craft.',
    ],
  },
  {
    handle: 'fountain-of-youth',
    name: 'Fountain of Youth',
    tagline: 'Intimate, feminine and genuinely tender, Fountain of Youth invites softness back into the way we care for ourselves, one slow, intentional moment at a time.',
    vendor_match: 'Fountain of Youth',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Fountain of Youth, known as FOY, was founded by Charlotte Keirle with a desire that feels quietly radical: to support women in developing a more loving, more attentive relationship with their own bodies.',
      'Made in New Zealand from a hand-crafted blend of organic botanical oils, FOY was created specifically to bring awareness, care and nourishment to breast tissue, encouraging healthy circulation and a more conscious, loving relationship with this often overlooked part of the body.',
      'Each formulation encourages care rather than correction, connection rather than critique, a way of tending to the body that begins with kindness.',
      'There is something deeply needed in what FOY offers, in a world that has forgotten how to be gentle with itself.',
    ],
  },
  {
    handle: 'frolic-ceramics',
    name: 'Frolic Ceramics',
    tagline: 'Tactile, joyful and warmly handmade, Frolic Ceramics brings ease and genuine character to the everyday domestic space.',
    vendor_match: 'Frolic Ceramics',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Vicki Fanning has been with us since the very beginning, one of our founding suppliers, and a maker whose work has lived in this space long enough to feel like it belongs here.',
      'A ceramist and glass artist of genuine standing, her work has been exhibited at galleries across Aotearoa including the Sarjeant Gallery and New Zealand Glassworks.',
      'Her Matakana studio, Frolic Ceramics, produces pieces across both ceramics and glass, shaped by an artist\'s sensitivity and a playful, generous hand.',
      'The work celebrates the studio process, the textures, the organic forms, the marks left by making, and is designed to be mixed, matched, held and truly lived with.',
      'Vicki\'s home studio is close by, and we are always happy to point you in her direction.',
    ],
  },
  {
    handle: 'hyoumankind',
    name: 'Hyoumankind',
    tagline: 'Restorative, considered and made with real care, Hyoumankind brings intention to one of our most essential and most undervalued rituals.',
    vendor_match: 'Hyoumankind',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Hyoumankind began in the home of founder Steph Wyborn. Steph spent over a decade trying to solve a problem that affects so many of us: how to actually sleep well.',
      'After years of research, collaboration with healthcare professionals and more than 20 prototypes, she created a range of ergonomic memory foam pillows designed to support proper alignment, prevent restless movement and help the body find genuine rest.',
      'Each product is shaped by genuine research into posture, alignment and the body\'s needs during sleep, not comfort as a vague aspiration, but rest as something that can be thoughtfully designed for.',
      'Made in New Zealand to the highest quality and now stocked at Harrods in London, Hyoumankind has earned its place as a deeply considered sleep brand.',
    ],
  },
  {
    handle: 'jan-haora',
    name: 'Jan Haora',
    tagline: 'Traditional, calming and made with genuine craft, Jan Haora offers a small and beautiful ritual of return.',
    vendor_match: 'Jan Haora',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Jan Haora makes beeswax ear candles in the tradition of Hopi design, a practice that is ancient, simple and built around a belief in the body\'s capacity for ease when given stillness and gentle attention.',
      'Each candle is crafted from natural materials and locally sourced New Zealand beeswax, made with care for the quiet ritual it is intended to support.',
      'The practice of ear candling is an unhurried one, something to be done with presence, in the kind of stillness that daily life rarely offers on its own.',
      'Jan Haora\'s approach honours that quality entirely, offering simple tools for those who believe in the value of pause and the wisdom of old, gentle forms of self-care.',
    ],
  },
  {
    handle: 'keller-bursten',
    name: 'Keller Bürsten',
    tagline: 'Honest, functional and enduringly beautiful, Keller Bürsten brings old-world care and quiet quality to the rituals of the everyday body.',
    vendor_match: 'Keller Bursten',
    collection_handle: '',
    published: false,
    paragraphs: [
      'More than 150 years of family heritage lives in a Keller Bürsten brush, in the weight of it, the feel of natural fibres against the skin, the quiet satisfaction of a tool made to last.',
      'Founded in 1869 by Johann Baptist Keller in Germany\'s Black Forest and now guided by the fifth generation of the same family, the brand has never wavered from its founding commitment to quality, natural materials and traditional craft.',
      'Its body, hand and nail brushes are crafted using carefully selected natural fibres and refined manufacturing techniques that have been passed down and quietly improved over more than a century. Almost all are made from wood, chosen for both its beauty and its low environmental footprint.',
      'A well-made brush used daily is one of the quietest forms of luxury, practical, beautiful and enduring in the way that only truly considered things can be.',
    ],
  },
  {
    handle: 'kinto',
    name: 'KINTO',
    tagline: 'Minimal, warm and deeply considered, KINTO brings beauty and intention to the smallest rituals of the day, the ones that, repeated daily, quietly shape a life.',
    vendor_match: 'KINTO',
    collection_handle: '',
    published: true,
    paragraphs: [
      'KINTO is a Japanese design brand founded in Hikone in 1972. From the very beginning it has been shaped by a single, quietly held belief: that practical objects should be simple, beautiful and genuinely easy to live with.',
      'Rooted in the Japanese concept of wabi sabi, the appreciation of beauty in imperfection and the passing of time, KINTO creates teaware, tableware and drinkware designed with balance, visual clarity and a quiet attention to the sensory details of daily use.',
      'Each piece invites the user to slow down and notice what they are doing, pouring, sitting, drinking, rather than moving through the moment without being present to it.',
      'There is a meditative quality to KINTO that is entirely appropriate for objects designed to accompany the ritual of tea.',
    ],
  },
  {
    handle: 'le-panier',
    name: 'Le Panier',
    tagline: 'Generous, tactile and quietly joyful, Le Panier brings ease, warmth and a touch of sun-warmed lightness into daily life.',
    vendor_match: 'Le Panier',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Le Panier baskets are designed in France and entirely handmade in Madagascar from raffia, a renewable natural fibre that carries the colour, warmth and unhurried beauty of the island it comes from.',
      'Each piece is made for everyday use, market days, beach mornings and the generous overflow of a well-stocked kitchen.',
      'The materials and forms are honest and unassuming, reflecting a relaxed way of living with natural objects where beauty is found in usefulness, in texture, in things that last.',
      'These are baskets made to be carried, to be filled and reached for again and again without thinking.',
    ],
  },
  {
    handle: 'le-verre-beldi',
    name: 'Le Verre Beldi',
    tagline: 'Warm, textured and full of quiet soul, Le Verre Beldi brings depth, history and the beauty of artisan craft to the everyday table.',
    vendor_match: 'Le Verre Beldi',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Morocco\'s only remaining hand-blown glass factory was nearly lost forever in 2013 when its owner abandoned it, leaving sixty skilled artisans without work. The Beldi group stepped in, reviving the tradition and moving production to their country club in Marrakech, where those same artisans continue the craft today.',
      'Beldi, meaning local or traditional in Arabic, has been synonymous with Moroccan daily life since the 1940s, the glass from which mint tea is poured, passed and shared across generations.',
      'Each piece is blown entirely by hand from locally recycled glass, clear glass from recycled bottles, green from beer glass, giving each piece its distinctive colour and the subtle irregularities that are the marks of genuine making.',
      'The collection is built for daily use, glasses to be filled and refilled, passed and returned, while quietly honouring the heritage and the reuse that give each piece its character.',
    ],
  },
  {
    handle: 'lisa-webb',
    name: 'Lisa Webb',
    tagline: 'Local, considered and genuinely beautiful, Lisa Webb creates jewellery that feels, from the very first time you wear it, like it was always meant to be yours.',
    vendor_match: 'Lisa Webb',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Lisa Webb has been making jewellery since childhood, when she first began crafting handmade gifts for the people she loved. That impulse, to make something meaningful and place it in someone else\'s hands, has never left her.',
      'She works from her studio in Matakana. Lisa is inspired by the natural world, drawing on the wild coastlines, shifting light and untamed landscapes of the Tāwharanui Peninsula, creating pieces that balance delicacy with quiet presence.',
      'Each piece is guided by an ethos of natural, comfortable sophistication, jewellery for the most authentic version of the self, where understated elegance meets something that feels a little bit like vintage glamour.',
      'Lisa works with a minimalist eye that nonetheless leaves room for feeling, pieces that nurture a simpler relationship with adornment while carrying enough character to be noticed and remembered.',
    ],
  },
  {
    handle: 'live-wild',
    name: 'Live Wild',
    tagline: 'Grounded in ancestral nutritional wisdom and formulated for the demands of modern life, Live Wild is a return to what the body has always known how to use.',
    vendor_match: 'Live Wild',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Amber Rose grew up foraging from her mother\'s organic garden in New Zealand, raised by a chef father and a mother who was honoured by the Queen for her services to heritage seed saving and regenerative agriculture. Food as medicine, food as story, food as connection to the land has been her life\'s work.',
      'After more than fifteen years in London as a food writer, art director and private chef, she returned to Aotearoa and launched a fermentation business from her kitchen table in Matakana that grew to supply supermarkets across New Zealand. Live Wild is the next expression of that same intention, blends built from organic and regeneratively grown wholefoods, designed to nourish rather than supplement.',
      'These are not products dressed up as food. They are food, made with the kind of knowledge that understands the difference between nourishment and convenience.',
      'Designed as a daily ritual, Live Wild supports hydration, resilience, clarity and steady energy without stimulants or quick fixes that borrow from tomorrow.',
    ],
  },
  {
    handle: 'maeve-ceramics',
    name: 'Maeve Ceramics',
    tagline: 'Handcrafted, considered and always evolving, Maeve Ceramics brings warmth and individuality to the objects of everyday life.',
    vendor_match: 'Maeve',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Maeve Ceramics is a collection of handmade pottery by Annie-Maeve, made one piece at a time in her Auckland studio, not far from the Matakana coast where her family calls home.',
      'Every piece is thrown by hand on the wheel, a process that is slow by nature and generous in what it gives back. Annie-Maeve is deeply committed to her craft, travelling the world to learn from other ceramic traditions and bringing that knowledge back to the studio with her.',
      'What is immediately striking about her work is the consistency she achieves across each piece. For a young ceramicist working entirely by hand, the precision and evenness across her collection is remarkable, a quiet sign of someone with a rare and genuine gift.',
      'The marks of the making are still present, the subtle variations in glaze and texture that remind you something was shaped by a human hand, but they sit within a body of work that feels considered and assured.',
      'From functional homewares to more decorative pieces, each object carries the quiet joy of a practice devoted entirely to the craft.',
    ],
  },
  {
    handle: 'mahurangi-olives',
    name: 'Mahurangi Olives',
    tagline: 'Rustic, generous and quietly ancient, Mahurangi Olives bring the nourishment of a working grove and the wisdom of old craft into everyday care.',
    vendor_match: 'Mahurangi Olives',
    collection_handle: '',
    published: true,
    paragraphs: [
      'On the shores of Mahurangi Harbour, surrounded by award-winning wineries and the quietly rolling hills of coastal Northland, more than a thousand mature olive trees grow across seven premium varieties, tended by Isabella and David Sullivan with genuine care for the land and its produce.',
      'From this grove, Mahurangi Olives produces extra virgin olive oil of exceptional purity and flavour, cold-pressed in small batches using traditional methods that honour the fruit and the land it comes from.',
      'The grove\'s Aleppo-style soap draws on an ancient Middle Eastern recipe, made from olive oil pressed on the property and blended with certified laurel berry oil brought directly from Turkey. Each bar is then cured for over a year. That unhurried process is what gives the soap its exceptional gentleness.',
      'Gentle and deeply nourishing, the soap works for face, body and hair, offering a beautifully simple and sustainable alternative to conventional cleansing.',
    ],
  },
  {
    handle: 'mangawhai-honey',
    name: 'Mangawhai Honey',
    tagline: 'Local, golden and deeply connected to the land that makes it, Mangawhai Honey carries the quiet sweetness of a place tended with love.',
    vendor_match: 'Mangawhai Honey',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Louis Smith\'s family has called Mangawhai home since his great grandfather purchased the land in the late 1940s. Mangawhai Honey, established in 2015, is the continuation of that deep and rooted relationship with this particular corner of Aotearoa.',
      'Louis tends his hives with the kind of care that understands honey as the product of an entire ecosystem, not just a single hive. He plants mānuka, kānuka, harakeke and tī kouka to nourish the biodiversity that supports his bees, an approach that sees the land and its living systems as partners rather than resources.',
      'We are proud to have Louis tend hives on our property in Te Arai, which means some of the honey we carry is made from the native flora of our land.',
      'Each jar carries the work and care of so many bees, the character of the land it comes from, its seasonal rhythms, its wildflowers, the specific quality of soil and air that makes honey from this place taste unmistakably of it.',
    ],
  },
  {
    handle: 'maryse',
    name: 'MARYSE',
    tagline: 'Refined, purposeful and elegantly restrained, MARYSE brings simplicity and considered intention to the daily practice of caring for skin.',
    vendor_match: 'MARYSE',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Maryse O\'Donnell spent years as a facialist before she began making her own formulations, watching closely how pure, plant-based products changed the skin over time and realising that what her clients needed didn\'t yet exist in quite the right form.',
      'She now works from a purpose-built blend studio in the garden of her Ponsonby home, formulating in small batches with a pared-back, unhurried approach that prioritises potency and integrity over quantity. Her first product, the Bio-Nutrient Face Oil, took nine months to perfect through ongoing trials with her clients. That same care and patience shapes everything she makes.',
      'MARYSE draws on New Zealand-native botanicals wherever possible, with a particular passion for mānuka leaf, sourced and finely milled on the East Cape, used in a way we haven\'t seen elsewhere in skincare.',
      'The result is skincare that works without announcing itself, that nourishes consistently, quietly and over time, in the way that the best things always do.',
    ],
  },
  {
    handle: 'melitta',
    name: 'Melitta',
    tagline: 'Considered, innovative and quietly determined, Melitta Skin is sun care made with the kind of integrity that this country\'s climate demands.',
    vendor_match: 'Melitta',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Melitta Adam grew up in South East Asia where sunscreen was barely a consideration, until she returned to Aotearoa and witnessed firsthand the damage of one of the world\'s harshest sun environments. That experience, combined with years working as a skin specialist, gave her both the knowledge and the urgency to create something better.',
      'After four years of development across laboratories in New Zealand, Australia, the United States and South Korea, she created GLOWGUARD, New Zealand\'s first daily-wear SPF 50+ with four hours of broad spectrum protection. Lightweight, fragrance-free and reef-safe, it sits beautifully under makeup and is designed to be worn with the same ease and intention as any other daily ritual.',
      'Formulated with botanicals chosen for their soothing, brightening and antioxidant qualities, GLOWGUARD supports a healthy skin barrier while protecting against UV damage.',
    ],
  },
  {
    handle: 'monarc-jewellery',
    name: 'Monarc Jewellery',
    tagline: 'Refined, conscious and quietly heirloom, Monarc Jewellery is adornment with lasting meaning, made to be worn, loved and one day passed on.',
    vendor_match: 'Monarc Jewellery',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Ella Drake grew up in Mount Maunganui and came to jewellery through an unexpected path, an international modelling career across Europe where she noticed that while fashion changed with every season, the jewellery people wore did not. That observation, and a deep discomfort with the untraceable origins of mined diamonds, led her to found Monarc in 2017 from a workspace in London\'s Hatton Garden.',
      'Monarc was built on a conviction that luxury and responsibility are not in tension. Every piece is made from 100% recycled precious metals and aboveground diamonds and gemstones, eliminating active mining entirely and working only with what is already in the world.',
      'In 2022, Monarc became the first jewellery brand in New Zealand to achieve B Corp certification, not as a marketing exercise but as a confirmation of practices already long in place.',
      'Each design balances contemporary form with the kind of timeless wearability that makes a piece feel as right in twenty years as it does the day it is first worn.',
    ],
  },
  {
    handle: 'monni-botanicals',
    name: 'Monni Botanicals',
    tagline: 'Grounded, considered and deeply connected to the land that sustains it, Monni Botanicals is an invitation to tend the skin the way we tend the earth, with patience, presence and love.',
    vendor_match: 'Monni Botanicals',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Monni Botanicals is a seed-to-bottle skincare line born from a deep collaboration between MONNI and The Herbologist, Hannah Jack, a maker whose knowledge of plants and their properties was passed down from her mother. The family farm in Kaukapakapa, north of Auckland, is home to over a hundred medicinal herbs and plants grown using organic and biodynamic practices.',
      'Hannah believes that what we put on our skin in the depths of winter should be entirely different from what we use in the height of summer, and that the energy and intention brought to the making of skincare is felt in the product itself. It is this philosophy that shapes every formulation, plants harvested at their seasonal peak, slowly infused into organic oils, combined with hand-crafted distillates to create skincare made with the intention and energy of the season, alive with the essence of the time and place it was made.',
      'At the heart of the range is the seasonal trio, a limited edition collection released at the beginning of each new season. What grows in a season becomes what nourishes the skin into the next, each trio carrying what the skin needs as the year turns.',
      'Native plants such as kawakawa, mānuka and horopito sit alongside calendula and seasonal wildflowers, and where plants are foraged or wild-harvested, this is done with care and respect, following Rongoā Māori principles, the traditional Māori system of healing grounded in a deep and reciprocal relationship between people, plants and the natural world.',
      'Because of this seasonal and small-batch approach, each product naturally varies in scent and colour, a quiet reflection of the time, place and plants from which it was made, and a reminder that real skincare is alive.',
    ],
  },
  {
    handle: 'monni-label',
    name: 'MONNI Label',
    tagline: 'Designed and made in Aotearoa New Zealand, MONNI Label is clothing as a form of self-expression, daily ritual and a quiet reminder that how we dress and how we live can be the same thing or a reflection of each other.',
    vendor_match: 'MONNI Label',
    collection_handle: '',
    published: true,
    paragraphs: [
      'MONNI Label is a vision of what clothing can be when every step is deeply considered. When it begins with love for yourself, for the natural world around you and the understanding that the two are not separate.',
      'Monni learned to sew at a young age, taught by her older sister, a seamstress and creative. Captured by fabric, movement and light she spent hours making outfits and mini collections, dressing her little sisters and photographing them in the garden.',
      'The dream of designing her own label never left her. When MONNI Label was brought to life she knew what it had to be, simple and elegant, made only from natural fibres, and created with the same intention she brings to everything else she makes.',
      'Monni became deeply interested in natural fibres, natural dyes and their relationship to the body. Long before she encountered the research, she could feel the difference. When she first wrapped herself in peace silk dyed with plants she could feel the energy of it, uplifting and comforting, a feeling that words can only gesture towards. The idea that clothing itself could be medicinal, dyed with herbs, worn close to the skin, our body\'s largest organ, never left her.',
      'Collections are made from the finest natural fibres, including peace silk, cotton, linen, New Zealand merino wool and carefully selected vintage fabrics, many of which might otherwise end up in landfill. MONNI Label works closely with natural plant dyers to create bespoke and limited edition pieces, using methods that honour the land and protect the waterways.',
      'Each piece is created with refined detailing and modern silhouettes designed to transcend season and trend, clothing made to be worn for years, not for a moment.',
      'There is a sensuality and groundedness to the label that is difficult to articulate but immediately felt when something is put on, a quality of ease and quiet empowerment that belongs entirely to garments made with this kind of intention.',
    ],
  },
  {
    handle: 'monni-art',
    name: 'MONNI Art',
    tagline: 'Rooted in whakapapa and expressed through beauty, Monique Jansen\'s art is a reminder that creativity can be an act of healing, for the artist and for the earth, and that our creativity and our making can exist in true harmony with the natural world.',
    vendor_match: 'Monique Jansen Art',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Monique Jansen is an artist of Dutch and Māori descent who has been making, painting and creating for as long as she can remember. Commissioned for her first artwork at seventeen, creating has been the thread running through her entire life, shaped by a deep love for nature and an evolving relationship with the land of her ancestors.',
      'In her twenties, Monni made the journey to her ancestral home, Te Araroa on the East Cape of New Zealand, the birthplace of her grandmother Charlotte Karaka. There she encountered the carvings of her grandmother\'s brother, a master carver whose extraordinary line work and storytelling left a profound mark. She returned home with a new understanding of what her own art could hold, and began developing the intricate fine-line style that defines her work today, following the contours of mountains she photographs, the horizon lines of landscapes she loves, and weaving into them the markings and stories of her whakapapa.',
      'One afternoon a quiet moment at the studio sink changed everything. Washing the paint from her brushes, she asked herself: if I wouldn\'t drink this, why would I put it into the earth? From that question, a new practice was born. She began making her own pigments from sustainably foraged native plants, drawing colour directly from the land itself.',
      'Each piece is made slowly, often over many months, using these natural pigments alongside Indian ink and calligraphy tools, capturing the look, light and feel of the land and interweaving story within every line. The work reflects the colours and textures of Aotearoa, the soft pink of pūriri bark, the earthy tones of windswept coastlines, the greens of native flora and the ever-changing shades of ocean blue. Each artwork is an offering, made with genuine care for the land it depicts.',
    ],
  },
  {
    handle: 'mothermade',
    name: 'MotherMade',
    tagline: 'Earthy, modern and quietly powerful, MotherMade brings ancient plant wisdom into the rhythms of contemporary wellbeing with honesty and grace.',
    vendor_match: 'Mother Made Mushrooms',
    collection_handle: '',
    published: true,
    paragraphs: [
      'MotherMade signals something, a departure from the era of man-made additives and synthetic shortcuts, and a return to the earth for remedies that have been trusted long before modern wellness made them fashionable.',
      'Founded by lifelong friends Emily Blanchett and Jessica Clarke, the brand is centred on 100% organic functional mushroom extracts, dual extracted from the fruiting body with no fillers or additives. Lion\'s Mane, Reishi, Chaga, Cordyceps and Turkey\'s Tail, each chosen for their deep and long-documented traditional use in supporting immunity, calm, clarity, vitality and restoration across centuries of practice.',
      'Each blend is designed to be woven effortlessly into daily ritual, from morning to evening, grounding and nourishing without overwhelm.',
      'Simpler, earthier forms of care where nothing is compromised, not the person who uses it, not the planet that provides it.',
    ],
  },
  {
    handle: 'nara',
    name: 'Nara',
    tagline: 'Gentle, pure and quietly purposeful, Nara is skincare made with love for the body that has given so much and the new one just arriving into the world.',
    vendor_match: 'Nara',
    collection_handle: '',
    published: true,
    paragraphs: [
      'The season of new motherhood asks for a different quality of care, quieter, more attentive, more tender than almost any other moment in a life.',
      'Nara was created by Kristi, a mother of three living on the New Zealand coast, whose own journey to natural living began during her first pregnancy. From that experience she began formulating her own range, products she would genuinely use on herself and her children, nourishment in its most natural form.',
      'Made in Aotearoa, every formula is built from pure botanical ingredients chosen for their safety, gentleness and genuine nourishment of the most delicate skin, free from toxins, fillers and anything that does not need to be there.',
      'The brand is guided by a deep respect for the earth these children will inherit, and a belief that the choices made in the earliest moments of a life can reflect the values we hope to pass on.',
    ],
  },
  {
    handle: 'nz-charly',
    name: 'NZ Charly',
    tagline: '',
    vendor_match: 'NZ Charly',
    collection_handle: '',
    published: false,
    paragraphs: [],
  },
  {
    handle: 'on-sundays',
    name: 'On Sundays',
    tagline: 'Gentle, reflective and deeply restorative, On Sundays brings softness and meaning to the rhythm of ordinary life, a reminder that the everyday can be made beautiful, one cup at a time.',
    vendor_match: 'On Sundays',
    collection_handle: '',
    published: true,
    paragraphs: [
      'On Sundays was born from founder Chenae\'s experience of burnout and a deep longing for moments of stillness, a desire to slow down, tread lightly and live more slowly.',
      'The brand explores balance through organic teas hand blended in New Zealand, using loose leaf only, with large cut leaves and flowers chosen for their nourishing qualities and their ability to invite the body to soften and the mind to settle. All teas are loose leaf, chosen for full transparency and the purest possible nourishment.',
      'Each blend is a quiet invitation to breathe, to notice, to return to the present before moving back into the demands of the day.',
    ],
  },
  {
    handle: 'people-of-the-earth',
    name: 'People of the Earth',
    tagline: 'Conscious, principled and quietly radical in its care, People of the Earth holds both the body and the living planet with equal devotion.',
    vendor_match: 'People of the Earth',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Freja and Julia founded People of the Earth as mothers and surfers living in Byron Bay, spending their days in the ocean and the sun. When they turned the bottle of sunscreen around and read the ingredients, they knew they could not unsee it. From that moment they set out to create something better.',
      'The brand\'s formulations are reef-safe, plastic-free and responsibly sourced, designed for use close to the ocean, the river, the forest, while leaving the lightest possible trace upon any of them. Fair wages for producers and ecologically safe practices across the entire supply chain are non-negotiable.',
      'Every ingredient and every material decision is considered through the lens of the ecosystems these products may eventually return to, the waterways we swim in, the soil we walk on, the ocean that connects everything.',
    ],
  },
  {
    handle: 'roger-orfevre',
    name: 'Roger Orfèvre',
    tagline: 'Timeless, practical and warmly domestic, these are everyday objects made with the rare understanding that longevity is its own form of sustainability.',
    vendor_match: 'Roger Orfèvre',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Roger Orfèvre has been making kitchen tools in Thiers, the cutlery capital of France, since 1924. A family owned company passed down through generations, it sits at the heart of a region with centuries of blade making heritage and an uncompromising understanding of what it means to make something well.',
      'The brand sources its solid wood standing, fells it, and stores it for two years before it ever reaches the workshop, a patience that speaks to everything Roger Orfèvre stands for. Its wooden tongs and utensils are crafted with function, simplicity and traditional craftsmanship as the only guides, natural material, honest making, a form that serves the hand.',
      'Each piece is designed to earn its place in a kitchen through daily use, to become familiar and indispensable over years of cooking, serving and gathering at the table.',
    ],
  },
  {
    handle: 'santosa',
    name: 'Santosa',
    tagline: 'Clean, mindful and softly grounding, Santosa brings calm intention and genuine care to the rituals of everyday domestic life.',
    vendor_match: 'Santosa',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Santosa is a Sanskrit word meaning contentment, a state of finding happiness and satisfaction in all that you do, starting with the simple everyday things. It is an apt name for a brand that believes the way we tend our homes is an extension of the way we tend ourselves.',
      'Born from a frustration with products that claimed to be eco-friendly but were not honest about what was inside them, Santosa set out to create something genuinely transparent, with only ingredients you can pronounce and nothing that doesn\'t need to be there.',
      'Formulations are free from harsh chemicals, preservatives, palm oil and synthetic fragrances, replaced instead with therapeutic essential oils that bring a grounding, sensory quality to even the most ordinary household task. Each product is batch-crafted in New Zealand with genuine care, turning the act of cleaning into something closer to ritual.',
    ],
  },
  {
    handle: 'sattva-soul',
    name: 'Sattva Soul',
    tagline: 'Warm, considered and quietly uplifting, Sattva Soul offers the kind of care that honours the whole self rather than treating it in parts.',
    vendor_match: 'Sattva Soul',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Sattva is a Sanskrit word that carries within it an entire way of being, balance, purity, a natural quality of ease that arises when the body and the mind are genuinely nourished.',
      'Founded by Celine Wallace, Sattva Soul was born from a deeply personal journey. Living and working as an actress in Hollywood, Celine\'s health began to fail, stress-induced seizures, adrenal fatigue and a nervous system pushed beyond its limits. She left everything behind and travelled to the Himalayas and Sri Lanka, where she spent years studying Ayurvedic medicine under the guidance of practitioners steeped in this ancient healing tradition. Using the herbs and practices she learned, she healed her own body.',
      'From these experiences Sattva Soul was born, first as a series of women\'s transformational retreats across New Zealand, Bali and the United States, and then as an organic Ayurvedic supplement line designed to bring those same healing tools into everyday life.',
      'Its supplements are made from herbs grown biodynamically on certified organic farms in the northern mountains of India and Sri Lanka, chosen for their therapeutic potency and their ability to support the body through stress, anxiety, poor sleep, hormonal shifts and adrenal fatigue.',
      'Each product is designed not as a quick fix but as a daily offering, nourishment for body, mind and spirit that accumulates gently over time into something that feels like genuine balance.',
    ],
  },
  {
    handle: 'soul-centre',
    name: 'SOUL Centre',
    tagline: 'Grounded, expansive and deeply human, SOUL offers something rare, a space where healing and belonging are not destinations but ways of being.',
    vendor_match: 'Soul Centre',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Wilhemeena Isabella Monroe is a mystic dance artist, poet, healer and teacher who has spent more than two decades creating spaces where people can come back to themselves.',
      'Founded in 2005 in Titirangi, on the edge of the rainforest in Aotearoa, SOUL, centre of the body and mind, was born from a vision to create a sanctuary where people could simply be, present to themselves through body, mind and spiritual practice. A community of people who love and care for the planet, and love and care for each other and themselves.',
      'A professional dancer for ten years before founding SOUL, Wilhemeena brings the wisdom of the body and the knowledge of movement into everything she offers. Her private practice spans bodywork, energy and spiritual healing, and plant medicine.',
      'Over two decades and thousands of people later, SOUL continues to offer workshops, retreats and deeply immersive programmes both in person and online, guided always by permaculture principles, regenerative practices and a belief that transformation begins with the willingness to truly arrive in oneself.',
      'Zen Mist was born from this same practice, a small distillation of everything SOUL holds, made to bring a moment of that grounding into everyday life.',
      'A social enterprise reinvesting in community, SOUL exists not to grow a business but to grow a world worth living in.',
    ],
  },
  {
    handle: 'storm-and-india',
    name: 'Storm & India',
    tagline: 'Joyful, nourishing and carrying the best kind of family legacy, Storm & India brings beauty and genuine care to the everyday ritual of the cup.',
    vendor_match: 'Storm & India',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Storm and India Bellamy grew up on their family\'s organic farm in Tasmania, with a mother, Dooley, who understood the nourishing power of a well-made cup. She spent years travelling the world studying the art of tea blending, growing her own herbs and keeping notebooks of recipes and blends she discovered along the way. That inheritance is present in everything Storm and India create.',
      'In 2015 the sisters brought those notebooks to life, handcrafting teas in small batches from certified organic herbs, spices, botanicals, fruits and vegetables, chosen with the dual intention of supporting the body and genuinely delighting the senses.',
      'Each blend is made with the belief that tea can be both functional and beautiful, that a daily cup of something carefully made is a small act of love for the body you live in. The range supports sleep, gut health, stress, energy and mood, everyday acts of care brewed into a cup.',
      'There is a familial warmth to Storm & India that comes through in the blends themselves, something bright, something soothing, something that feels like it was made with you in mind.',
    ],
  },
  {
    handle: 'sunhouse-chai',
    name: 'Sunhouse Chai',
    tagline: 'Rich, carefully made and full of warmth, Sunhouse Chai brings spice, sweetness and the best kind of ceremony into daily ritual.',
    vendor_match: 'Sunhouse Chai',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Chai is one of the world\'s oldest warming rituals, a practice of spice, sweetness and shared comfort that has travelled across cultures and centuries without losing any of its power.',
      'Sunhouse Chai was created on a small organic farm in Upper Moutere, at the top of New Zealand\'s South Island, to honour that tradition and bring to it the quality it deserves. Made from certified organic whole spices, organic Assam tea leaves, ginger root and turmeric granules, each blend is hand-blended in small batches and sweetened with raw wilderness honey from the same region, a formulation that is as honest as it is delicious.',
      'The range includes both traditional and caffeine-free rooibos alternatives, offering a spiced ritual for the early morning, the slow afternoon or the moment at the end of the day when warmth is what is needed most.',
      'Each cup is grounding, aromatic and genuinely comforting, the kind of thing that makes whatever moment you are in feel a little more nourished.',
    ],
  },
  {
    handle: 'superfeast',
    name: 'SuperFeast',
    tagline: 'Grounded in Taoist tradition and formulated for modern life, SuperFeast brings one of the world\'s oldest healing systems into the rhythms of everyday wellbeing.',
    vendor_match: 'SuperFeast',
    collection_handle: '',
    published: false,
    paragraphs: [
      'For thousands of years, Taoist herbalists understood something that modern wellness is only beginning to rediscover, that the most powerful medicine grows slowly, in specific places, tended by people who understand what they are working with.',
      'Mason Taylor began SuperFeast in 2011 from his mother\'s home in Sydney, driven by a single conviction, that the world\'s most potent medicinal mushrooms and tonic herbs should be accessible to everyone, not just practitioners.',
      'What started as a personal search for quality became Australia\'s leading supplier of Dì Dào tonic herbs and mushrooms. Dì Dào, a Chinese concept meaning local to the land, refers to herbs grown and harvested in the specific regions where they have been cultivated for thousands of years, the pristine mountains and valleys of China where the traditions of Taoist herbalism were born.',
      'SuperFeast works exclusively with this standard, sourcing Reishi, Lion\'s Mane, Chaga, Cordyceps and other medicinal mushrooms from their place of origin, where the soil, climate and centuries of knowledge combine to produce herbs of genuine therapeutic potency.',
      'The brand is 100% family owned, run by Mason and his wife Tahnee, guided by the same grassroots values present on day one. A belief that a business is an ecosystem, and that everyone it touches should be left better than it found them.',
    ],
  },
  {
    handle: 'suzanne-day',
    name: 'Suzanne Day',
    tagline: 'Poetic, thoughtful and gently mystical, Suzanne Day creates things that hold light, and ask you, softly, to pay closer attention.',
    vendor_match: 'Suzanne Day',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Suzanne Day moves between graphic design, jewellery making, astrology, tarot, plant medicine and alchemy as if they were not separate disciplines at all but different languages for the same inquiry into beauty, meaning and the nature of things.',
      'From this wide and wandering sensibility, she creates cards and objects that carry something beyond the decorative, a quality of harmony, detail and emotional resonance that is difficult to name but immediately felt.',
      'Each piece seems to arrive already meaningful, as if it has been waiting for the right person rather than being made for anyone in particular.',
      'Her work invites reflection and a more careful, attentive relationship with the world, with the symbols that recur, the patterns that persist, the quiet magic that lives in considered objects.',
    ],
  },
  {
    handle: 'tahi',
    name: 'Tahi',
    tagline: 'Earthy, purposeful and woven into the whenua, Tahi offers a daily ritual of belonging, skincare as a form of quiet connection to the land and to oneself.',
    vendor_match: 'Tahi',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Tahi begins from a single, grounding belief, that we are part of nature, not separate from it. Its guiding ethos, Kotahi Tātou, we are one, shapes everything it makes.',
      'Founded by Jackie Lee and Nathan Christy, the brand was born from a conviction that useful traditions have been lost and that what was once simple has become unnecessarily complicated. Each oil blend is made with native botanicals from Aotearoa, kawakawa, harakeke, koromiko and mānuka, chosen for their relationship to skin and to the living world, and formulated with a deep reverence for the land and the wisdom it holds.',
      'Jackie handmakes each oil with the care and presence that comes from genuine connection to both the product and its purpose, formulations that feel as honest as the land they draw from.',
      'There is an intimacy to Tahi that is immediately apparent, this is not skincare made at scale or distance, but something close, considered and made by people who believe deeply in what they are doing.',
    ],
  },
  {
    handle: 'ti-point-olives',
    name: 'Ti Point Olives',
    tagline: 'Coastal, golden and generous in the way that only genuinely local things can be, Ti Point Olives brings the richness of a specific and beloved place to the table.',
    vendor_match: 'Ti Point Olives',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Ti Point sits on a volcanic headland along the Northland coast, free-draining soils, high sunshine hours and water drawn from a pure aquifer 42 metres below the surface creating conditions quietly extraordinary for the cultivation of olives. The grove is nestled amongst basalt rock outcrops that extend all the way down to the sea.',
      'Each harvest is gathered by hand by friends, family and members of the local community, a collective effort that carries the warmth of shared work and a deep connection to both the land and each other.',
      'The olives are then cold-pressed into single-grove extra virgin olive oil that carries the particular character of this place, the sea air, the volcanic earth, the light of the Northland coast.',
      'You cannot replicate what a harvest made this way produces, and that difference is entirely present in every bottle.',
    ],
  },
  {
    handle: 'vania',
    name: 'VANIA',
    tagline: 'Luxurious, free-spirited and softly timeless, VANIA offers jewellery with genuine movement and soul, pieces that feel as personal as the person wearing them.',
    vendor_match: 'Vania Jewellery',
    collection_handle: '',
    published: true,
    paragraphs: [
      'Vania Truchsess grew up in Maracaibo, Venezuela, raised by her parents and by Dionicia, a woman from the Wayuu tribe who looked after her as a child and who gave her, through the quiet act of knitting traditional Wayuu bags, a lifelong love of handmade things.',
      'She moved to New Zealand in 2012, carrying that love and a wandering spirit shaped by travel, music, gemstones and the colours of changing seasons. After working jobs that didn\'t capture her heart, she took the leap in 2017 and founded VANIA, a jewellery brand for dreamers, lovers and wandering souls, handcrafted in Auckland using natural gemstones and precious metals.',
      'Each piece is designed with a free and feeling sensibility, effortless and luxurious, timeless with a gypsy edge, made for those who choose jewellery not as an accessory but as an expression of something true about themselves.',
    ],
  },
  {
    handle: 'wild-and-indigo',
    name: 'Wild & Indigo',
    tagline: 'Fluid, feminine and quietly extraordinary, Wild & Indigo offers something that no industrial process could replicate, beauty drawn directly, honestly and lovingly from the earth.',
    vendor_match: 'Wild & Indigo',
    collection_handle: '',
    published: false,
    paragraphs: [
      'Janna Isbey makes textiles the way the natural world makes colour, slowly, unpredictably and with a beauty that no deliberate process could fully plan for.',
      'Her practice, Wild & Indigo, is rooted in natural dyeing, a craft she has deepened through years of travel and study with specialist artisans in India, Japan and Bali. Working with silk, flowers and foraged plant matter, she uses eco dyeing, eco printing, shibori, batik and block printing to create scarves and textiles where colour is gathered from the landscape itself rather than manufactured from it.',
      'Each piece is made slowly, the plants given time to leave their particular marks, softness, tone, the faintest gradations of hue that shift depending on the light and the hour. Janna describes the process as a collaboration between the artist\'s hand and the imprint of Mother Nature, an energy that is beautiful to look at and intuitively healthy for the soul.',
    ],
  },
];
